# Generated by Django 4.1.1 on 2022-09-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
